### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by seanherron** [m6tt/HelpLess#1]
Hey there,

I'm using LESS.app on my Mac (http://incident57.com/less/) and am running into an issue when trying to compile thing using HelpLess. Here's my LESS:

``` CSS
a {
  display:inline-block;
  padding:5px;
  background:#ccc;
  #hl.round-all-corners(10px);
}
```

This returns the following when I try to compile:

```
Syntax Error on lin 909 in helpless.0.0.3.less
908 color:#ccc;
909 .text-shadow(1px, 1px #333;
910 }

#hl.round-all-corners is undefined in style.css
82 hl#round-all-corners(10px);
```

Any ideas as to what could be causing this?

Thanks!

PS: I'm using less-boilerplate as well.
